---
- hosts: mywebserver
  become: yes
  tasks:
  - name: Install java on Ubuntu
    apt:
      name: "{{myjavaonubuntu}}"
      state: present 
    when: ansible_os_family == "Debian"

  - name: Installing java on Redhat 
    yum:
      name: "{{myjavaonredhat}}"
      state: present 
    when: ansible_os_family == "RedHat"