--- 
- hosts: 172.31.35.184
  become: yes
  tasks: 
  - name: execute linux command
    command: hostname -f 
    register: myhostname

  - name: want to display 
    debug:
      msg: "{{myhostname}}"