--- 
- hosts: 172.31.35.184
  become: yes
  tasks:
  - name: Install git
    apt: 
      name: git
      state: present 
  
  - name: Install tree 
    apt:
      name: tree
      stateeee: present 
    ignore_errors: true 

  - name: Install wget 
    apt: 
      name: wget
      state: present 