--- 
- hosts: 172.31.35.184
  become: yes
  tasks: 
  - name: Install webserver
    apt:
      name: apache2
      state: present 

  - name: copy file
    copy:
      src: mystaticfile.txt
      dest: /home/ubuntu/myfile2.txt 

  - name: copying index.j2 template to ansible nodes
    template:
      src: mystaticfile.txt
      dest: /var/www/html/index.html

  
      