--- 
- hosts: 172.31.35.184
  become: yes
  tasks: 
  - name: Install webserver
    apt:
      name: apache2
      state: present 

  - name: copy file
    copy:
      src: mystatic.txt
      dest: /home/ubuntu/myfile2.txt 