
--- 
- hosts: all 
  become: yes
  tasks:
  - name: Installing Apache2 webserver
    apt:
      name: apache2
      state: present 
  - name: Starting service 
    service:
      name: apache2
      state: restarted
