
--- 
- hosts: all 
  become: yes
  tasks:
  - name: Installing Apache2 webserver
    apt:
      name: apache2
      state: present 
    when: ansible_os_family == "Debian"
  - name: Starting service 
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"

  - name: I want to install webserver on RedHat 
    yum:
      name: httpd
      state: present 
    when: ansible_os_family == "RedHat"
  - name: I want to start httpd server
    service:
      name: httpd
      state: present 
    when: ansible_os_family == "RedHat"
