
--- 
- hosts: all 
  become: yes
  tasks:
  - name: Installing Apache2 webserver
    apt:
      name: apache2
      state: present 
    when: ansible_os_family == "Debian"
  - name: Starting service 
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"
