--- 
- name: deploy application
  get_url: 
    url: https://mys3bucket080723.s3.amazonaws.com/spring-petclinic-3.1.0-SNAPSHOT.jar
    dest: /opt/tomcat/webapps/spring-petclinic-3.1.0-SNAPSHOT.jar
    force_basic_auth: yes