--- 
- name: download tomcat 
  get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.34/bin/apache-tomcat-9.0.34.tar.gz
    dest: /home/ubuntu/apache-tomcat-9.0.34.tar.gz
    force_basic_auth: yes

- name: Create a tomcat folder
  file:
    path: /opt/tomcat
    state: directory


- name: extract tomcat 
  command:
    cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-9.0.34.tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE